
import Nav from "./components/Nav"
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
      <title>Ivak Dev Market</title>
      </head>
      <body>
      <div className="border-b p-6 bg-gradient-to-b from-yellow-950 to-yellow-100">
      <Nav/> 
        {children}
      </div>
      </body>
    </html>
  )
}
