
import Nav from "./components/Nav"
export const metadata = {
  title: 'Ivak Nft market',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
      <title>Ivak Dev Market</title>
      {/* <link rel="shortcut icon" href="frank.png" /> */}
      <a href="https://www.flaticon.com/free-icons/spooky" title="spooky icons">Spooky icons created by Freepik - Flaticon</a>
      </head>
      <body>
      <div className="border-b p-6 bg-gradient-to-b from-yellow-950 to-yellow-100">
      <Nav/> 
        {children}
      </div>
      </body>
    </html>
  )
}
